export type Domain = 'sleep' | 'mind' | 'heart' | 'immune' | 'body' | 'eyes'

export type Concern = 'low' | 'high' | 'both'

export interface Indicator {
  id: string
  label: string
  short: string
  domain: Domain
  unit: string
  kind: 'number' | 'scale' | 'flag'
  concern: Concern
  /** Smallest change that matters; floors the spread so a very steady baseline does not flag noise. */
  minSpread: number
  min?: number
  max?: number
  step?: number
  /** Labels for 1..5 scales, low to high. */
  scaleLabels?: [string, string]
  /** Hard limit that triggers action regardless of baseline. */
  hard?: { op: '>=' | '<='; value: number; note: string }
  help: string
}

export const DOMAINS: { id: Domain; name: string; why: string }[] = [
  {
    id: 'sleep',
    name: 'Sleep',
    why: 'Crews sleep about six hours a night in flight, and short sleep compounds every other risk.',
  },
  {
    id: 'mind',
    name: 'Mind and mood',
    why: 'Isolation and confinement change mood and alertness slowly enough that it is easy to miss in yourself.',
  },
  {
    id: 'heart',
    name: 'Heart and circulation',
    why: 'Fluid shifts toward the head and the heart works against less load, which changes pulse and pressure.',
  },
  {
    id: 'immune',
    name: 'Immune signs',
    why: 'Latent viruses reactivate and immune regulation shifts in flight. Early symptoms are the first thing you can see.',
  },
  {
    id: 'body',
    name: 'Bone and muscle',
    why: 'Without load, bone and muscle are lost every week. Exercise and body mass are the levers you control.',
  },
  {
    id: 'eyes',
    name: 'Eyes and head',
    why: 'Fluid shift can change near vision and cause headaches over long missions.',
  },
]

export const INDICATORS: Indicator[] = [
  {
    id: 'sleepHours',
    label: 'Sleep last night',
    short: 'Sleep',
    domain: 'sleep',
    unit: 'h',
    kind: 'number',
    concern: 'low',
    minSpread: 0.5,
    min: 0,
    max: 14,
    step: 0.25,
    help: 'Hours actually asleep, not hours in the sleep station.',
  },
  {
    id: 'sleepQuality',
    label: 'Sleep quality',
    short: 'Sleep quality',
    domain: 'sleep',
    unit: '',
    kind: 'scale',
    concern: 'low',
    minSpread: 0.6,
    scaleLabels: ['Poor', 'Restful'],
    help: 'How rested you feel after waking.',
  },
  {
    id: 'mood',
    label: 'Mood',
    short: 'Mood',
    domain: 'mind',
    unit: '',
    kind: 'scale',
    concern: 'low',
    minSpread: 0.6,
    scaleLabels: ['Low', 'Good'],
    help: 'Your overall mood across the last day.',
  },
  {
    id: 'stress',
    label: 'Stress',
    short: 'Stress',
    domain: 'mind',
    unit: '',
    kind: 'scale',
    concern: 'high',
    minSpread: 0.6,
    scaleLabels: ['Calm', 'Strained'],
    help: 'How much pressure you felt from work, crew or home.',
  },
  {
    id: 'connected',
    label: 'Connection to crew and home',
    short: 'Connection',
    domain: 'mind',
    unit: '',
    kind: 'scale',
    concern: 'low',
    minSpread: 0.6,
    scaleLabels: ['Isolated', 'Connected'],
    help: 'How connected you felt to the people around you and at home.',
  },
  {
    id: 'reactionMs',
    label: 'Reaction time',
    short: 'Reaction',
    domain: 'mind',
    unit: 'ms',
    kind: 'number',
    concern: 'high',
    minSpread: 15,
    min: 100,
    max: 2000,
    step: 1,
    help: 'Median from the 3-minute vigilance test. Run it at the same time each day.',
  },
  {
    id: 'lapses',
    label: 'Attention lapses',
    short: 'Lapses',
    domain: 'mind',
    unit: '',
    kind: 'number',
    concern: 'high',
    minSpread: 1,
    min: 0,
    max: 100,
    step: 1,
    help: 'Responses slower than 355 ms in the vigilance test.',
  },
  {
    id: 'restingHr',
    label: 'Resting heart rate',
    short: 'Resting HR',
    domain: 'heart',
    unit: 'bpm',
    kind: 'number',
    concern: 'both',
    minSpread: 3,
    min: 30,
    max: 200,
    step: 1,
    help: 'Measured after waking, before coffee or exercise.',
  },
  {
    id: 'systolic',
    label: 'Blood pressure, systolic',
    short: 'Systolic',
    domain: 'heart',
    unit: 'mmHg',
    kind: 'number',
    concern: 'both',
    minSpread: 5,
    min: 60,
    max: 240,
    step: 1,
    hard: { op: '>=', value: 140, note: '140 mmHg or higher is in the hypertensive range' },
    help: 'Upper number from the cuff.',
  },
  {
    id: 'diastolic',
    label: 'Blood pressure, diastolic',
    short: 'Diastolic',
    domain: 'heart',
    unit: 'mmHg',
    kind: 'number',
    concern: 'both',
    minSpread: 4,
    min: 30,
    max: 160,
    step: 1,
    hard: { op: '>=', value: 90, note: '90 mmHg or higher is in the hypertensive range' },
    help: 'Lower number from the cuff.',
  },
  {
    id: 'temperature',
    label: 'Body temperature',
    short: 'Temperature',
    domain: 'immune',
    unit: '°C',
    kind: 'number',
    concern: 'high',
    minSpread: 0.25,
    min: 34,
    max: 42,
    step: 0.1,
    hard: { op: '>=', value: 38, note: '38.0 °C or higher is a fever' },
    help: 'Oral or ear temperature.',
  },
  {
    id: 'symptoms',
    label: 'Immune symptoms',
    short: 'Symptoms',
    domain: 'immune',
    unit: '',
    kind: 'number',
    concern: 'high',
    minSpread: 1,
    min: 0,
    max: 8,
    step: 1,
    hard: { op: '>=', value: 2, note: 'two or more immune symptoms on the same day' },
    help: 'Counted from the symptom list.',
  },
  {
    id: 'exerciseMin',
    label: 'Exercise completed',
    short: 'Exercise',
    domain: 'body',
    unit: 'min',
    kind: 'number',
    concern: 'low',
    minSpread: 10,
    min: 0,
    max: 300,
    step: 5,
    help: 'Resistive and aerobic minutes combined.',
  },
  {
    id: 'bodyMass',
    label: 'Body mass',
    short: 'Body mass',
    domain: 'body',
    unit: 'kg',
    kind: 'number',
    concern: 'low',
    minSpread: 0.5,
    min: 30,
    max: 160,
    step: 0.1,
    help: 'From the mass measurement device, same time of day.',
  },
  {
    id: 'backPain',
    label: 'Back pain',
    short: 'Back pain',
    domain: 'body',
    unit: '/10',
    kind: 'number',
    concern: 'high',
    minSpread: 1,
    min: 0,
    max: 10,
    step: 1,
    help: '0 is none, 10 is the worst you can imagine.',
  },
  {
    id: 'headache',
    label: 'Headache',
    short: 'Headache',
    domain: 'eyes',
    unit: '/10',
    kind: 'number',
    concern: 'high',
    minSpread: 1,
    min: 0,
    max: 10,
    step: 1,
    help: '0 is none, 10 is the worst you can imagine.',
  },
  {
    id: 'nearVision',
    label: 'Near vision changed',
    short: 'Near vision',
    domain: 'eyes',
    unit: '',
    kind: 'flag',
    concern: 'high',
    minSpread: 1,
    hard: { op: '>=', value: 1, note: 'any new change in near vision' },
    help: 'Print or screens look blurrier up close than before flight.',
  },
]

export const SYMPTOMS = [
  { id: 'soreThroat', label: 'Sore throat' },
  { id: 'congestion', label: 'Congestion or runny nose' },
  { id: 'cough', label: 'Cough' },
  { id: 'rash', label: 'Skin rash or itch' },
  { id: 'lipLesion', label: 'Cold sore or lip blister' },
  { id: 'fatigue', label: 'Unusual fatigue' },
  { id: 'chills', label: 'Chills or aches' },
  { id: 'gi', label: 'Nausea or upset stomach' },
] as const

export type SymptomId = (typeof SYMPTOMS)[number]['id']

export const byId = Object.fromEntries(INDICATORS.map((i) => [i.id, i])) as Record<string, Indicator>
